message = "Custom domains are not supported. See https://github.com/cockroachdb/cockroach/issues/27796"
exclude :test_text_defaults_in_new_schema_when_overriding_domain, message
exclude :test_string_defaults_in_new_schema_when_overriding_domain, message
exclude :test_decimal_defaults_in_new_schema_when_overriding_domain, message
exclude :test_bpchar_defaults_in_new_schema_when_overriding_domain, message
exclude :test_text_defaults_after_updating_column_default, message
exclude :test_default_containing_quote_and_colons, message
