exclude :test_bulk_insert_multiple_table_with_a_multi_statement_query, "Skipping until we can triage further. See https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/48"
exclude :test_bulk_insert_with_a_multi_statement_query_in_a_nested_transaction, "Skipping until we can triage further. See https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/48"
exclude :test_clean_fixtures, "Skipping"
exclude :test_auto_value_on_primary_key, "Skipping"
exclude :test_create_fixtures, "Skipping"
exclude :test_yaml_file_with_symbol_columns, "Skipping"
exclude :test_bulk_insert, "Skipping"
exclude :test_multiple_clean_fixtures, "Skipping"
exclude :test_bulk_insert_with_a_multi_statement_query_raises_an_exception_when_any_insert_fails, "Skipping"
exclude :test_inserts_with_pre_and_suffix, "Skipping"
exclude :test_create_symbol_fixtures, "Skipping"
