exclude :test_where_with_integer_for_string_column_using_bind_parameters, "Skipping because StatementInvalid exception is not being raised for unknown reason."
exclude :test_where_with_rational_for_string_column_using_bind_parameters, "Skipping because StatementInvalid exception is not being raised for unknown reason."
exclude :test_where_with_float_for_string_column_using_bind_parameters, "Skipping because StatementInvalid exception is not being raised for unknown reason."
exclude :test_where_with_decimal_for_string_column_using_bind_parameters, "Skipping because StatementInvalid exception is not being raised for unknown reason."
exclude :test_where_with_duration_for_string_column_using_bind_parameters, "Skipping because StatementInvalid exception is not being raised for unknown reason."
