exclude :test_create_join_table, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_set_not_null_by_default, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_with_strings, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_with_symbol_and_string, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_with_the_proper_order, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_with_the_table_name, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_with_the_table_name_as_string, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_with_column_options, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_with_uuid, "Join tables in CockroachDB must have a pk, but PG omits these unless explicitly specified"
exclude :test_create_join_table_with_index, "Results of an operation cannot be accessed prior to completion of that operation's transaction. See https://www.cockroachlabs.com/docs/v19.2/architecture/transaction-layer.html#transaction-conflicts"
exclude :test_create_and_drop_join_table_with_common_prefix, "Results of an operation cannot be accessed prior to completion of that operation's transaction. See https://www.cockroachlabs.com/docs/v19.2/architecture/transaction-layer.html#transaction-conflicts"
