exclude :test_add_foreign_key_inferes_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_foreign_key_with_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_on_delete_restrict_foreign_key, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_on_delete_cascade_foreign_key, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_on_delete_nullify_foreign_key, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_foreign_key_with_on_update, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_foreign_key_exists, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_foreign_key_exists_by_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_foreign_key_exists_by_name, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_remove_foreign_key_inferes_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_remove_foreign_key_by_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_remove_foreign_key_by_symbol_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_remove_foreign_key_by_name, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_invalid_foreign_key, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_validate_foreign_key_infers_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_validate_foreign_key_by_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_validate_foreign_key_by_symbol_column, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_validate_foreign_key_by_name, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_validate_constraint_by_name, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_schema_dumping, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_schema_dumping_on_delete_and_on_update_options, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_foreign_key_is_reversible, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_foreign_key_constraint_is_not_cached_incorrectly, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_foreign_key_with_prefix, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_add_foreign_key_with_suffix, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
exclude :test_foreign_keys, "Skipping until we can triage further. See https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/48"
exclude :test_schema_dumping_with_options, "Skipping until we can triage further. See https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/48"
exclude :test_remove_foreign_key_by_the_select_one_on_the_same_table, "This test fails due to the transactional nature of the test. Disabling transactions will make the test pass."
