exclude :test_change_string_to_date, "Changing column data types is not supported in a transaction in CockroachDB. See https://github.com/cockroachdb/cockroach/issues/9851."
exclude :test_change_type_with_symbol, "Changing column data types is not supported in a transaction in CockroachDB. See https://github.com/cockroachdb/cockroach/issues/9851."
exclude :test_change_type_with_symbol_with_timestamptz, "Changing column data types is not supported in a transaction in CockroachDB. See https://github.com/cockroachdb/cockroach/issues/9851."
exclude :test_change_type_with_symbol_using_datetime, "Changing column data types is not supported in a transaction in CockroachDB. See https://github.com/cockroachdb/cockroach/issues/9851."
exclude :test_change_type_with_symbol_using_timestamp_with_timestamptz_as_default, "Changing column data types is not supported in a transaction in CockroachDB. See https://github.com/cockroachdb/cockroach/issues/9851."
exclude :test_change_type_with_symbol_with_timestamptz_as_default, "Changing column data types is not supported in a transaction in CockroachDB. See https://github.com/cockroachdb/cockroach/issues/9851."
exclude :test_change_type_with_symbol_using_datetime_with_timestamptz_as_default, "Changing column data types is not supported in a transaction in CockroachDB. See https://github.com/cockroachdb/cockroach/issues/9851."
exclude :test_change_type_with_array, "Changing column data types is not supported in a transaction in CockroachDB. See https://github.com/cockroachdb/cockroach/issues/9851."
